//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SectionsEC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SectionsEC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Material xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Concrete&gt;
        ///    &lt;Concrete&gt;
        ///      &lt;Grade&gt;C12/15&lt;/Grade&gt;
        ///      &lt;Fck&gt;12000&lt;/Fck&gt;
        ///      &lt;Acc&gt;1&lt;/Acc&gt;
        ///      &lt;GammaC&gt;1.5&lt;/GammaC&gt;
        ///      &lt;N&gt;2&lt;/N&gt;
        ///      &lt;Ec2&gt;0.002&lt;/Ec2&gt;
        ///      &lt;Ecu2&gt;0.0035&lt;/Ecu2&gt;
        ///    &lt;/Concrete&gt;
        ///    &lt;Concrete&gt;
        ///      &lt;Grade&gt;C16/20&lt;/Grade&gt;
        ///      &lt;Fck&gt;16000&lt;/Fck&gt;
        ///      &lt;Acc&gt;1&lt;/Acc&gt;
        ///      &lt;GammaC&gt;1.5&lt;/GammaC&gt;
        ///      &lt;N&gt;2&lt;/N&gt;
        ///      &lt;Ec2&gt;0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string materials {
            get {
                return ResourceManager.GetString("materials", resourceCulture);
            }
        }
    }
}
